/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doanthibanglai;

import java.util.ArrayList;
import java.util.Collections;
import readexcel.CauHoi;

/**
 *
 * @author DASH ST
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Duong dan File excel CauHoi
                String excelFileCauLietPath = "src\\FileExcelCauHoi\\CauLiet.xlsx";
                String excelFileCauLyThuyetPath = "src\\FileExcelCauHoi\\CauLyThuyet.xlsx";
                String excelFileCauSaHinhPath = "src\\FileExcelCauHoi\\CauSaHinh.xlsx";
                String excelFileCauBienBaoPath = "src\\FileExcelCauHoi\\CauBienBao.xlsx";

                ArrayList<CauHoi> dsCauLiet = ReadExcel.readCauHoiFromExcel(excelFileCauLietPath);
                ArrayList<CauHoi> dsCauLyThuyet = ReadExcel.readCauHoiFromExcel(excelFileCauLyThuyetPath);
                ArrayList<CauHoi> dsCauSaHinh = ReadExcel.readCauHoiFromExcel(excelFileCauSaHinhPath);
                ArrayList<CauHoi> dsCauBienBao = ReadExcel.readCauHoiFromExcel(excelFileCauBienBaoPath);

                // Duong dan File anh CauHoi
                String FileImageCauLietPath = "src\\ImageCauHoi\\CauLietImage";
                String FileImageCauBienBaoPath = "src\\ImageCauHoi\\CauBienBaoImage";
                String FileImageCauSaHinhPath = "src\\ImageCauHoi\\CauSaHinhImage";
                String FileImageCauLyThuyetPath = "src\\ImageCauHoi\\CauLyThuyetImage";

                ReadExcel.addImagePath(dsCauLiet, FileImageCauLietPath);
                ReadExcel.addImagePath(dsCauLyThuyet, FileImageCauLyThuyetPath);
                ReadExcel.addImagePath(dsCauBienBao, FileImageCauBienBaoPath);
                ReadExcel.addImagePath(dsCauSaHinh, FileImageCauSaHinhPath);
                     
                // Tao danh sach Cau Hoi Thi
                ArrayList<CauHoi> dsCauHoiThi = new ArrayList<>();
                int soCauLyThuyet = 6; 
                int soCauLiet = 3;
                int soCauBienBao = 6;
                int soCauSaHinh = 5;

                ReadExcel.randomAddCauHoi(dsCauHoiThi, dsCauLyThuyet, soCauLyThuyet);
                ReadExcel.randomAddCauHoi(dsCauHoiThi, dsCauBienBao, soCauBienBao);
                ReadExcel.randomAddCauHoi(dsCauHoiThi, dsCauSaHinh, soCauSaHinh);
                ReadExcel.randomAddCauHoi(dsCauHoiThi, dsCauLiet, soCauLiet);
                Collections.shuffle(dsCauHoiThi); // Xao tron danh sach thi

                System.out.println(dsCauHoiThi.size());
                for (CauHoi cauHoi : dsCauHoiThi) {

                    System.out.println(cauHoi);

                }
                
                new JFrameManHinhChinh();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
